JA\AppBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        avatar:
            groups: [Default]
        ownedGames:
            groups: [Default]
            recursion_groups:
                add: [list]
                remove: [details]
